apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e17mxukao-dotnet-basic
  janus-idp.io/tekton: e17mxukao-dotnet-basic
  backstage.io/kubernetes-id: e17mxukao-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e17mxukao-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
